// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — AccountsStack — aws_organizations_account resources
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import { Stack, aws_organizations as orgs } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';

export interface AccountsStackProps extends LzStackProps {
  // OU path -> id, from OrganizationsStack.ouIds. Each account parents to its
  // declared OU; if a path is somehow absent we fall back to a placeholder
  // token (search-and-replace before deploy) rather than crash the synth.
  readonly ouIds: Record<string, string>;
}

interface AccountSpec {
  readonly name: string;
  readonly email: string;
  readonly ouPath: string;       // OU path the account parents to (e.g. Workloads/Prod/PHI)
  readonly description?: string;
}

export class AccountsStack extends Stack {
  public readonly accountIds: Record<string, string> = {};

  constructor(scope: Construct, id: string, props: AccountsStackProps) {
    super(scope, id, props);

    const accounts: AccountSpec[] = [
      {
        name:        'LogArchive',
        email:       "PLACEHOLDER_EMAIL_LogArchive@example.com",
        ouPath:      'Security',
        description: 'Central log archive',
      },
      {
        name:        'Audit',
        email:       "PLACEHOLDER_EMAIL_Audit@example.com",
        ouPath:      'Security',
        description: 'Security tooling delegated administrator',
      },
      {
        name:        'SharedServices',
        email:       "PLACEHOLDER_EMAIL_SharedServices@example.com",
        ouPath:      'Infrastructure',
        description: 'Shared services',
      },
      {
        name:        'Network',
        email:       "PLACEHOLDER_EMAIL_Network@example.com",
        ouPath:      'Infrastructure',
        description: 'Central network hub',
      },
      {
        name:        "AppSandbox",
        email:       "aws-app-sandbox@example.com",
        ouPath:      "Workloads/Sandbox",
        description: "Application sandbox / experimentation",
      },
      {
        name:        "AppDev",
        email:       "aws-app-dev@example.com",
        ouPath:      "Workloads/Dev",
        description: "Application development",
      },
      {
        name:        "AppStaging",
        email:       "aws-app-staging@example.com",
        ouPath:      "Workloads/Staging",
        description: "Application staging / pre-prod",
      },
      {
        name:        "AppProd",
        email:       "aws-app-prod@example.com",
        ouPath:      "Workloads/Prod",
        description: "Application production",
      },
    ];

    // OU id token for a path not in the SoT map — a search-and-replace marker.
    const placeholderOuId = (path: string) =>
      `PLACEHOLDER_OU_ID_${path.replace(/[^A-Za-z0-9]/g, '')}`;

    for (const a of accounts) {
      const ouRef = props.ouIds[a.ouPath] ?? placeholderOuId(a.ouPath);
      const acct = new orgs.CfnAccount(this, `${a.name}Account`, {
        accountName: a.name,
        email:       a.email,
        parentIds:   [ouRef],
        roleName:    "OrganizationAccountAccessRole",
      });
      this.accountIds[a.name] = acct.attrAccountId;
    }
  }
}