// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — BackupStack — AWS Backup vault + daily plan
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import { Stack, aws_backup as backup, aws_kms as kms, aws_iam as iam,
  aws_events as events, Duration, RemovalPolicy } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';

export interface BackupStackProps extends LzStackProps {
  // When true, this stack is deployed to the DR region and creates ONLY the
  // cross-region copy vault + a region-local CMK to encrypt it. The primary
  // BackupStack references that vault by ARN in its copyActions.
  readonly drVault?: boolean;
}

export class BackupStack extends Stack {
  constructor(scope: Construct, id: string, props: BackupStackProps) {
    super(scope, id, props);

    if (props.drVault) {
      // DR-region copy vault. A regional outage must not take the recovery
      // points (or their key) with it, so the key lives here in the DR region
      // rather than replicating the (possibly HSM-bound) accelerator key. A CMK
      // is required by CKV_AWS_166 and keeps the copies under a CMK in the same
      // sovereignty boundary as the vault.
      const drKey = new kms.Key(this, 'BackupDrKey', {
        alias:             'alias/accelerator/kms/backup-dr-key',
        description:       'CMK for the cross-region AWS Backup copy vault',
        enableKeyRotation: true,
        rotationPeriod:    Duration.days(365),
        removalPolicy:     RemovalPolicy.RETAIN,
      });
      new backup.BackupVault(this, 'CentralVaultDr', {
        backupVaultName: "central-vault-dr",
        encryptionKey:   drKey,
        removalPolicy:   RemovalPolicy.RETAIN,
        lockConfiguration: {
          changeableFor:   Duration.days(3),
          minRetention:    Duration.days(7),
          maxRetention:    Duration.days(2555),
        },
      });
      return;
    }

    const acceleratorKey = kms.Key.fromLookup(this, 'AcceleratorKey', {
      aliasName: 'alias/accelerator/kms/key',
    });

    const vault = new backup.BackupVault(this, 'CentralVault', {
      backupVaultName: "central-vault",
      encryptionKey:   acceleratorKey,
      removalPolicy:   RemovalPolicy.RETAIN,
      lockConfiguration: {
        changeableFor:   Duration.days(3),
        minRetention:    Duration.days(7),
        maxRetention:    Duration.days(2555),
      },
    });

    const plan = new backup.BackupPlan(this, 'DailyPlan', {
      backupPlanName: `${props.orgName.toLowerCase()}-daily`,
      backupPlanRules: [
        new backup.BackupPlanRule({
          ruleName:           'DailyAtMidnightUTC',
          backupVault:        vault,
          scheduleExpression: events.Schedule.cron({ hour: '5', minute: '0' }),
          startWindow:        Duration.minutes(60),
          completionWindow:   Duration.minutes(180),
          moveToColdStorageAfter: Duration.days(30),
          deleteAfter:        Duration.days(2555),
          // Replicate each daily recovery point to the DR region (warm standby).
          // The destination vault is created by the sibling BackupDrStack
          // (BackupStack with drVault:true) deployed to eu-west-1,
          // and is CMK-encrypted there.
          copyActions: [{
            destinationBackupVault: backup.BackupVault.fromBackupVaultArn(this, 'DrVaultRef',
              `arn:aws:backup:eu-west-1:${this.account}:backup-vault:${ "central-vault" }-dr`),
            moveToColdStorageAfter: Duration.days(30),
            deleteAfter:            Duration.days(2555),
          }],
          recoveryPointTags:  props.tags,
        }),
      ],
    });

    plan.addSelection('DailyTagSelection', {
      backupSelectionName: 'daily-tagged',
      resources:           [backup.BackupResource.fromTag('Backup', 'true')],
      role:                new iam.Role(this, 'BackupServiceRole', {
        assumedBy:       new iam.ServicePrincipal('backup.amazonaws.com'),
        managedPolicies: [
          iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSBackupServiceRolePolicyForBackup'),
          iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSBackupServiceRolePolicyForRestores'),
        ],
      }),
    });
  }
}