// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — ConfigStack — AWS Config recorder + delivery channel + aggregator + managed rules
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import {
  Stack,
  aws_config as config,
  aws_iam as iam,
  aws_s3 as s3,
} from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';
import { LoggingStack } from './logging-stack';

export interface ConfigStackProps extends LzStackProps {
  /** Wire from LoggingStack so the delivery-channel bucket name is the
   *  exact bucket the LoggingStack created, with no string drift. */
  readonly loggingStack: LoggingStack;
}

/**
 * CIS 3.5: AWS Config must be enabled in every region of every member
 * account. This stack creates the recorder + delivery channel locally,
 * and an organization-level aggregator in the Audit account so findings
 * roll up centrally.
 */
export class ConfigStack extends Stack {
  constructor(scope: Construct, id: string, props: ConfigStackProps) {
    super(scope, id, props);

    const role = new iam.Role(this, 'ConfigRole', {
      assumedBy: new iam.ServicePrincipal('config.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWS_ConfigRole'),
      ],
    });

    new config.CfnConfigurationRecorder(this, 'ConfigRecorder', {
      name:     'default',
      roleArn:  role.roleArn,
      recordingGroup: {
        allSupported:               true,
        includeGlobalResourceTypes: true,
      },
    });

    const deliveryChannel = new config.CfnDeliveryChannel(this, 'ConfigDeliveryChannel', {
      name:         'default',
      s3BucketName: props.loggingStack.centralLogsBucket.bucketName,
      s3KeyPrefix:  'config',
      configSnapshotDeliveryProperties: {
        deliveryFrequency: 'TwentyFour_Hours',
      },
    });
    deliveryChannel.node.addDependency(props.loggingStack.centralLogsBucket);

    // Organization aggregator (deployed in the Audit account in real
    // deployments; placeholder in CDK assumes this stack runs there).
    new config.CfnConfigurationAggregator(this, 'OrgAggregator', {
      configurationAggregatorName: 'org-aggregator',
      organizationAggregationSource: {
        roleArn:    role.roleArn,
        allAwsRegions: true,
      },
    });

    // Managed rules — baseline CIS / NIST surface.
    const managedRules: Array<{ id: string; sourceId: string; description: string; }> = [
      { id: 'RootMfaEnabled',          sourceId: 'ROOT_ACCOUNT_MFA_ENABLED',           description: 'CIS 1.13 — root account must have MFA' },
      { id: 'IamPasswordPolicy',       sourceId: 'IAM_PASSWORD_POLICY',                description: 'CIS 1.8/1.10 — password policy meets baseline' },
      { id: 'S3BucketPublicReadProhibited',  sourceId: 'S3_BUCKET_PUBLIC_READ_PROHIBITED',  description: 'CIS 2.1.5 — no public S3 read' },
      { id: 'S3BucketPublicWriteProhibited', sourceId: 'S3_BUCKET_PUBLIC_WRITE_PROHIBITED', description: 'CIS 2.1.5 — no public S3 write' },
      { id: 'EbsEncryptedVolumes',     sourceId: 'ENCRYPTED_VOLUMES',                  description: 'CIS 2.2.1 — EBS volumes encrypted' },
      { id: 'RdsStorageEncrypted',     sourceId: 'RDS_STORAGE_ENCRYPTED',              description: 'CIS 2.3.1 — RDS storage encrypted' },
    ];
    managedRules.forEach(r => {
      new config.CfnConfigRule(this, r.id, {
        configRuleName: r.id,
        description:    r.description,
        source: {
          owner:           'AWS',
          sourceIdentifier: r.sourceId,
        },
      });
    });
  }
}