// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — CostStack — Budgets + Cost Anomaly Detection
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import { Stack, aws_budgets as budgets, aws_ce as ce } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';

export class CostStack extends Stack {
  constructor(scope: Construct, id: string, props: LzStackProps) {
    super(scope, id, props);

    new budgets.CfnBudget(this, "OrgMonthlyBudget", {
      budget: {
        budgetName:     "org-monthly",
        budgetType:     'COST',
        budgetLimit:    { amount: 100000, unit: 'USD' },
        timeUnit:       'MONTHLY',
        costTypes: {
          includeCredit:            false,
          includeDiscount:          true,
          includeOtherSubscription: true,
          includeRecurring:         true,
          includeRefund:            false,
          includeSubscription:      true,
          includeSupport:           true,
          includeTax:               true,
          includeUpfront:           true,
          useAmortized:             false,
          useBlended:               false,
        },
      },
      notificationsWithSubscribers: [
        {
          notification: {
            comparisonOperator: 'GREATER_THAN',
            notificationType:   'ACTUAL',
            threshold:          80,
            thresholdType:      'PERCENTAGE',
          },
          subscribers: [
            { address: "my3mail@acme.com", subscriptionType: 'EMAIL' },
          ],
        },
        {
          notification: {
            comparisonOperator: 'GREATER_THAN',
            notificationType:   'FORECASTED',
            threshold:          100,
            thresholdType:      'PERCENTAGE',
          },
          subscribers: [
            { address: "my3mail@acme.com", subscriptionType: 'EMAIL' },
          ],
        },
      ],
    });
    new budgets.CfnBudget(this, "WorkloadsProdBudget", {
      budget: {
        budgetName:     "workloads-prod",
        budgetType:     'COST',
        budgetLimit:    { amount: 50000, unit: 'USD' },
        timeUnit:       'MONTHLY',
        costTypes: {
          includeCredit:            false,
          includeDiscount:          true,
          includeOtherSubscription: true,
          includeRecurring:         true,
          includeRefund:            false,
          includeSubscription:      true,
          includeSupport:           true,
          includeTax:               true,
          includeUpfront:           true,
          useAmortized:             false,
          useBlended:               false,
        },
      },
      notificationsWithSubscribers: [
        {
          notification: {
            comparisonOperator: 'GREATER_THAN',
            notificationType:   'ACTUAL',
            threshold:          80,
            thresholdType:      'PERCENTAGE',
          },
          subscribers: [
            { address: "my3mail@acme.com", subscriptionType: 'EMAIL' },
          ],
        },
        {
          notification: {
            comparisonOperator: 'GREATER_THAN',
            notificationType:   'FORECASTED',
            threshold:          100,
            thresholdType:      'PERCENTAGE',
          },
          subscribers: [
            { address: "my3mail@acme.com", subscriptionType: 'EMAIL' },
          ],
        },
      ],
    });
    new budgets.CfnBudget(this, "WorkloadsNonprodBudget", {
      budget: {
        budgetName:     "workloads-nonprod",
        budgetType:     'COST',
        budgetLimit:    { amount: 20000, unit: 'USD' },
        timeUnit:       'MONTHLY',
        costTypes: {
          includeCredit:            false,
          includeDiscount:          true,
          includeOtherSubscription: true,
          includeRecurring:         true,
          includeRefund:            false,
          includeSubscription:      true,
          includeSupport:           true,
          includeTax:               true,
          includeUpfront:           true,
          useAmortized:             false,
          useBlended:               false,
        },
      },
      notificationsWithSubscribers: [
        {
          notification: {
            comparisonOperator: 'GREATER_THAN',
            notificationType:   'ACTUAL',
            threshold:          90,
            thresholdType:      'PERCENTAGE',
          },
          subscribers: [
            { address: "my3mail@acme.com", subscriptionType: 'EMAIL' },
          ],
        },
        {
          notification: {
            comparisonOperator: 'GREATER_THAN',
            notificationType:   'FORECASTED',
            threshold:          110,
            thresholdType:      'PERCENTAGE',
          },
          subscribers: [
            { address: "my3mail@acme.com", subscriptionType: 'EMAIL' },
          ],
        },
      ],
    });
    const monitor = new ce.CfnAnomalyMonitor(this, 'ServiceAnomalyMonitor', {
      monitorName:      'service-anomaly-monitor',
      monitorType:      'DIMENSIONAL',
      monitorDimension: 'SERVICE',
    });

    new ce.CfnAnomalySubscription(this, 'AnomalyEmailSub', {
      subscriptionName: 'anomaly-subscription',
      frequency:        'DAILY',
      monitorArnList:   [monitor.attrMonitorArn],
      subscribers:      [{ type: 'EMAIL', address: "my3mail@acme.com" }],
      thresholdExpression: JSON.stringify({
        Dimensions: {
          Key:         'ANOMALY_TOTAL_IMPACT_ABSOLUTE',
          Values:      [500],
          MatchOptions: ['GREATER_THAN_OR_EQUAL'],
        },
      }),
    });
  }
}