// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — IamStack — IAM Identity Center permission sets + workload roles
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import { Stack, aws_sso as sso, aws_iam as iam, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';

export class IamStack extends Stack {
  constructor(scope: Construct, id: string, props: LzStackProps) {
    super(scope, id, props);

    // Identity Center instance ARN must be supplied via context (CDK cannot create the instance).
    const instanceArn = this.node.tryGetContext('identityCenterInstanceArn') as string
      ?? 'PLACEHOLDER_ARN_IdentityCenter';

    new sso.CfnPermissionSet(this, 'AdministratorAccess', {
      name:                       'AdministratorAccess',
      description:                'Full administrative access. Restrict via SCP.',
      instanceArn,
      sessionDuration:            'PT1H',
      managedPolicies:            ['arn:aws:iam::aws:policy/AdministratorAccess'],
    });

    new sso.CfnPermissionSet(this, 'PowerUserAccess', {
      name:                       'PowerUserAccess',
      description:                'Power user access (no IAM/Org/Billing).',
      instanceArn,
      sessionDuration:            'PT8H',
      managedPolicies:            ['arn:aws:iam::aws:policy/PowerUserAccess'],
    });

    new sso.CfnPermissionSet(this, 'ReadOnlyAccess', {
      name:                       'ReadOnlyAccess',
      description:                'Read-only across services.',
      instanceArn,
      sessionDuration:            'PT8H',
      managedPolicies:            ['arn:aws:iam::aws:policy/ReadOnlyAccess'],
    });

    new sso.CfnPermissionSet(this, 'BillingAccess', {
      name:            'BillingAccess',
      description:     'Read-only billing + cost explorer.',
      instanceArn,
      sessionDuration: 'PT4H',
      managedPolicies: ['arn:aws:iam::aws:policy/job-function/Billing'],
    });

    new sso.CfnPermissionSet(this, 'SecurityAuditAccess', {
      name:            'SecurityAuditAccess',
      description:     'SecurityAudit + ReadOnly.',
      instanceArn,
      sessionDuration: 'PT8H',
      managedPolicies: [
        'arn:aws:iam::aws:policy/SecurityAudit',
        'arn:aws:iam::aws:policy/ReadOnlyAccess',
      ],
    });

    // Break-glass IAM role
    new iam.Role(this, 'BreakGlassRole', {
      roleName:        'BreakGlassRole',
      assumedBy:       new iam.ArnPrincipal(`arn:aws:iam::${props.env?.account}:root`),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('AdministratorAccess')],
      maxSessionDuration: undefined,
    });

    const oidcProviders: Record<string, iam.OpenIdConnectProvider> = {};    oidcProviders["GitHubActions"] = new iam.OpenIdConnectProvider(this, "GithubactionsOidc", {
      url:          "https://token.actions.githubusercontent.com",
      clientIds:    ["sts.amazonaws.com"],
    });

    new iam.Role(this, "TerraformexecutorRole", {
      roleName:           "TerraformExecutor",
      description:        "Spacelift / CI Terraform executor with boundary",
      maxSessionDuration: Duration.seconds(3600),
      assumedBy: new iam.WebIdentityPrincipal(
        oidcProviders["GitHubActions"].openIdConnectProviderArn, {
          StringEquals: { "token.actions.githubusercontent.com:aud": "sts.amazonaws.com" },
          StringLike:   { "token.actions.githubusercontent.com:sub": 'repo:PLACEHOLDER_GIT_ORG/PLACEHOLDER_GIT_REPO:*' },
        }),
      permissionsBoundary: iam.ManagedPolicy.fromManagedPolicyArn(this, "TerraformexecutorBoundary", "AdministratorAccessBoundary"),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName("AdministratorAccess"),
      ],
    });
  }
}