// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — KmsReplicaStack — central-logs CMK replica in the DR region
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import { Stack, aws_kms as kms } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';

export interface KmsReplicaStackProps extends LzStackProps {
  // ARN of the multi-region primary key (KmsStack.centralLogsKey), passed
  // cross-region via crossRegionReferences.
  readonly primaryKeyArn: string;
}

export class KmsReplicaStack extends Stack {
  constructor(scope: Construct, id: string, props: KmsReplicaStackProps) {
    super(scope, id, props);

    // DR replica of the central-logs CMK. Same key material as the primary;
    // the matching alias lets the replicated log bucket in this region decrypt
    // its SSE-KMS objects. Policy mirrors the primary (generators/aws_kms_principals.py).
    const replica = new kms.CfnReplicaKey(this, 'CentralLogsReplica', {
      primaryKeyArn:       props.primaryKeyArn,
      description:         'DR replica of central-logs CMK',
      pendingWindowInDays: 30,
      keyPolicy:           {"Statement": [{"Action": "kms:*", "Effect": "Allow", "Principal": {"AWS": "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_LogArchive:root"}, "Resource": "*", "Sid": "EnableRoot"}, {"Action": ["kms:GenerateDataKey*", "kms:DescribeKey"], "Condition": {"StringLike": {"aws:SourceArn": ["arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_Management:trail/*", "arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_LogArchive:trail/*"], "kms:EncryptionContext:aws:cloudtrail:arn": ["arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_Management:trail/*", "arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_LogArchive:trail/*"]}}, "Effect": "Allow", "Principal": {"Service": "cloudtrail.amazonaws.com"}, "Resource": "*", "Sid": "AllowCloudtrail"}, {"Action": ["kms:GenerateDataKey*", "kms:Decrypt", "kms:DescribeKey"], "Condition": {"StringEquals": {"aws:SourceOrgID": "PLACEHOLDER_ORG_ID"}}, "Effect": "Allow", "Principal": {"Service": "config.amazonaws.com"}, "Resource": "*", "Sid": "AllowConfig"}, {"Action": ["kms:GenerateDataKey*", "kms:Decrypt", "kms:DescribeKey"], "Condition": {"StringEquals": {"aws:SourceOrgID": "PLACEHOLDER_ORG_ID"}}, "Effect": "Allow", "Principal": {"Service": "delivery.logs.amazonaws.com"}, "Resource": "*", "Sid": "AllowDeliverylogs"}, {"Action": ["kms:GenerateDataKey*", "kms:Decrypt", "kms:DescribeKey"], "Condition": {"StringEquals": {"aws:SourceAccount": "PLACEHOLDER_ACCOUNT_ID_LogArchive"}}, "Effect": "Allow", "Principal": {"Service": "s3.amazonaws.com"}, "Resource": "*", "Sid": "AllowS3"}], "Version": "2012-10-17"},
    });

    new kms.CfnAlias(this, 'CentralLogsReplicaAlias', {
      aliasName:   'alias/accelerator/kms/central-logs-key',
      targetKeyId: replica.attrKeyId,
    });
  }
}