// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — KmsStack — customer-managed CMKs (accelerator + central-logs + workload)
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import { Stack, aws_kms as kms, aws_iam as iam, RemovalPolicy, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';


export class KmsStack extends Stack {
  public readonly acceleratorKey: kms.IKey;
  public readonly centralLogsKey: kms.IKey;

  constructor(scope: Construct, id: string, props: LzStackProps) {
    super(scope, id, props);

    // HSM-backed CMKs (FIPS 140-2 Level 3). values.kms_use_hsm is set, so each
    // CMK is created as a CfnKey bound to a CloudHSM custom key store via
    // origin = AWS_CLOUDHSM + customKeyStoreId. Replace
    // PLACEHOLDER_CLOUDHSM_KEY_STORE_ID with the real cks-xxxxxxxx after
    // running through HSM_SETUP.md (see DEPLOYMENT_GUIDE.md and PLACEHOLDERS.md).

    const acceleratorCfnKey = new kms.CfnKey(this, 'AcceleratorCfnKey', {
      description: 'Default AWS LZA-managed CMK (HSM-backed)',
      enableKeyRotation: true,
      rotationPeriodInDays: 365,
      keyUsage: 'ENCRYPT_DECRYPT',
      keySpec: 'SYMMETRIC_DEFAULT',
      pendingWindowInDays: 30,
      origin: 'AWS_CLOUDHSM',
      customKeyStoreId: 'PLACEHOLDER_CLOUDHSM_KEY_STORE_ID',
      keyPolicy: {
        Version: '2012-10-17',
        Statement: [{
          Sid: 'EnableRoot',
          Effect: 'Allow',
          Principal: { AWS: `arn:aws:iam::${Stack.of(this).account}:root` },
          Action: 'kms:*',
          Resource: '*',
        }],
      },
    });
    acceleratorCfnKey.applyRemovalPolicy(RemovalPolicy.RETAIN);
    new kms.CfnAlias(this, 'AcceleratorKeyAlias', {
      aliasName: 'alias/accelerator/kms/key',
      targetKeyId: acceleratorCfnKey.attrKeyId,
    });
    this.acceleratorKey = kms.Key.fromKeyArn(this, 'AcceleratorKey', acceleratorCfnKey.attrArn);

    const centralLogsCfnKey = new kms.CfnKey(this, 'CentralLogsCfnKey', {
      description: 'CMK for central log archive and CloudTrail org trail (HSM-backed)',
      enableKeyRotation: true,
      rotationPeriodInDays: 365,
      keyUsage: 'ENCRYPT_DECRYPT',
      keySpec: 'SYMMETRIC_DEFAULT',
      multiRegion: true,
      pendingWindowInDays: 30,
      origin: 'AWS_CLOUDHSM',
      customKeyStoreId: 'PLACEHOLDER_CLOUDHSM_KEY_STORE_ID',
      keyPolicy: {"Statement": [{"Action": "kms:*", "Effect": "Allow", "Principal": {"AWS": "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_LogArchive:root"}, "Resource": "*", "Sid": "EnableRoot"}, {"Action": ["kms:GenerateDataKey*", "kms:DescribeKey"], "Condition": {"StringLike": {"aws:SourceArn": ["arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_Management:trail/*", "arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_LogArchive:trail/*"], "kms:EncryptionContext:aws:cloudtrail:arn": ["arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_Management:trail/*", "arn:aws:cloudtrail:*:PLACEHOLDER_ACCOUNT_ID_LogArchive:trail/*"]}}, "Effect": "Allow", "Principal": {"Service": "cloudtrail.amazonaws.com"}, "Resource": "*", "Sid": "AllowCloudtrail"}, {"Action": ["kms:GenerateDataKey*", "kms:Decrypt", "kms:DescribeKey"], "Condition": {"StringEquals": {"aws:SourceOrgID": "PLACEHOLDER_ORG_ID"}}, "Effect": "Allow", "Principal": {"Service": "config.amazonaws.com"}, "Resource": "*", "Sid": "AllowConfig"}, {"Action": ["kms:GenerateDataKey*", "kms:Decrypt", "kms:DescribeKey"], "Condition": {"StringEquals": {"aws:SourceOrgID": "PLACEHOLDER_ORG_ID"}}, "Effect": "Allow", "Principal": {"Service": "delivery.logs.amazonaws.com"}, "Resource": "*", "Sid": "AllowDeliverylogs"}, {"Action": ["kms:GenerateDataKey*", "kms:Decrypt", "kms:DescribeKey"], "Condition": {"StringEquals": {"aws:SourceAccount": "PLACEHOLDER_ACCOUNT_ID_LogArchive"}}, "Effect": "Allow", "Principal": {"Service": "s3.amazonaws.com"}, "Resource": "*", "Sid": "AllowS3"}], "Version": "2012-10-17"},
    });
    centralLogsCfnKey.applyRemovalPolicy(RemovalPolicy.RETAIN);
    new kms.CfnAlias(this, 'CentralLogsKeyAlias', {
      aliasName: 'alias/accelerator/kms/central-logs-key',
      targetKeyId: centralLogsCfnKey.attrKeyId,
    });
    this.centralLogsKey = kms.Key.fromKeyArn(this, 'CentralLogsKey', centralLogsCfnKey.attrArn);
    // iam is unused in HSM mode (service principals are baked into keyPolicy);
    // a reference keeps the import live so the file compiles under strict TS.
    void iam;

    const workloadDefaultCfnKey = new kms.CfnKey(this, "WorkloadDefaultCfnKey", {
      description: "Default workload CMK",
      enableKeyRotation: true,
      rotationPeriodInDays: 365,
      keyUsage: 'ENCRYPT_DECRYPT',
      keySpec: 'SYMMETRIC_DEFAULT',
      multiRegion: true,
      pendingWindowInDays: 30,
      origin: 'AWS_CLOUDHSM',
      customKeyStoreId: 'PLACEHOLDER_CLOUDHSM_KEY_STORE_ID',
      keyPolicy: {
        Version: '2012-10-17',
        Statement: [{
          Sid: 'EnableRoot',
          Effect: 'Allow',
          Principal: { AWS: `arn:aws:iam::${Stack.of(this).account}:root` },
          Action: 'kms:*',
          Resource: '*',
        }],
      },
    });
    workloadDefaultCfnKey.applyRemovalPolicy(RemovalPolicy.RETAIN);
    new kms.CfnAlias(this, "WorkloadDefaultKeyAlias", {
      aliasName: "alias/workload/default",
      targetKeyId: workloadDefaultCfnKey.attrKeyId,
    });
    const s3ObjectsCfnKey = new kms.CfnKey(this, "S3ObjectsCfnKey", {
      description: "S3 SSE-KMS CMK",
      enableKeyRotation: true,
      rotationPeriodInDays: 365,
      keyUsage: 'ENCRYPT_DECRYPT',
      keySpec: 'SYMMETRIC_DEFAULT',
      multiRegion: false,
      pendingWindowInDays: 30,
      origin: 'AWS_CLOUDHSM',
      customKeyStoreId: 'PLACEHOLDER_CLOUDHSM_KEY_STORE_ID',
      keyPolicy: {
        Version: '2012-10-17',
        Statement: [{
          Sid: 'EnableRoot',
          Effect: 'Allow',
          Principal: { AWS: `arn:aws:iam::${Stack.of(this).account}:root` },
          Action: 'kms:*',
          Resource: '*',
        }],
      },
    });
    s3ObjectsCfnKey.applyRemovalPolicy(RemovalPolicy.RETAIN);
    new kms.CfnAlias(this, "S3ObjectsKeyAlias", {
      aliasName: "alias/workload/s3-objects",
      targetKeyId: s3ObjectsCfnKey.attrKeyId,
    });
    const rdsCfnKey = new kms.CfnKey(this, "RdsCfnKey", {
      description: "RDS encryption CMK",
      enableKeyRotation: true,
      rotationPeriodInDays: 365,
      keyUsage: 'ENCRYPT_DECRYPT',
      keySpec: 'SYMMETRIC_DEFAULT',
      multiRegion: false,
      pendingWindowInDays: 30,
      origin: 'AWS_CLOUDHSM',
      customKeyStoreId: 'PLACEHOLDER_CLOUDHSM_KEY_STORE_ID',
      keyPolicy: {
        Version: '2012-10-17',
        Statement: [{
          Sid: 'EnableRoot',
          Effect: 'Allow',
          Principal: { AWS: `arn:aws:iam::${Stack.of(this).account}:root` },
          Action: 'kms:*',
          Resource: '*',
        }],
      },
    });
    rdsCfnKey.applyRemovalPolicy(RemovalPolicy.RETAIN);
    new kms.CfnAlias(this, "RdsKeyAlias", {
      aliasName: "alias/workload/rds",
      targetKeyId: rdsCfnKey.attrKeyId,
    });
  }
}