// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — LoggingStack — central S3 log archive + org CloudTrail
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import { Stack, aws_s3 as s3, aws_kms as kms, aws_cloudtrail as ct, aws_iam as iam,
  aws_logs as logs, RemovalPolicy, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';

export class LoggingStack extends Stack {
  public readonly centralLogsBucket: s3.Bucket;

  constructor(scope: Construct, id: string, props: LzStackProps) {
    super(scope, id, props);

    // Look up the central-logs CMK (provisioned in KmsStack)
    const centralLogsKey = kms.Key.fromLookup(this, 'CentralLogsKey', {
      aliasName: 'alias/accelerator/kms/central-logs-key',
    });

    this.centralLogsBucket = new s3.Bucket(this, 'CentralLogsBucket', {
      bucketName:           `${props.orgName.toLowerCase()}-central-logs-${this.account}`.substring(0, 63),
      encryption:           s3.BucketEncryption.KMS,
      encryptionKey:        centralLogsKey,
      bucketKeyEnabled:     true,
      versioned:            true,
      enforceSSL:           true,
      blockPublicAccess:    s3.BlockPublicAccess.BLOCK_ALL,
      removalPolicy:        RemovalPolicy.RETAIN,
      lifecycleRules: [
        {
          enabled:                true,
          abortIncompleteMultipartUploadAfter: Duration.days(7),
          noncurrentVersionExpiration:         Duration.days(90),
          expiration:                          Duration.days(1825),
          transitions: [
            { storageClass: s3.StorageClass.INFREQUENT_ACCESS, transitionAfter: Duration.days(90)  },
            { storageClass: s3.StorageClass.GLACIER,           transitionAfter: Duration.days(365) },
          ],
        },
      ],
    });

    // Permit CloudTrail + Config to write
    this.centralLogsBucket.addToResourcePolicy(new iam.PolicyStatement({
      sid:       'AWSCloudTrailWrite',
      effect:    iam.Effect.ALLOW,
      principals:[new iam.ServicePrincipal('cloudtrail.amazonaws.com')],
      actions:   ['s3:PutObject'],
      resources: [`${this.centralLogsBucket.bucketArn}/cloudtrail/*`],
      conditions:{ StringEquals: { 's3:x-amz-acl': 'bucket-owner-full-control' } },
    }));

    // Organization trail — feature flags from
    // generators/aws_cloudtrail_features.py so every format ships the
    // same trail config for a given compliance set.
    const trail = new ct.Trail(this, 'OrgTrail', {
      trailName:                    "acmecorp-org-trail",
      bucket:                       this.centralLogsBucket,
      s3KeyPrefix:                  'cloudtrail',
      encryptionKey:                centralLogsKey,
      isOrganizationTrail:          true,
      isMultiRegionTrail:           true,
      includeGlobalServiceEvents:   true,
      enableFileValidation:         true,
      sendToCloudWatchLogs:         true,
      // Compliance frameworks with a >=1y audit-log floor raise this to ONE_YEAR
      // (CKV_AWS_338); matches the OpenTofu/LZA/tfvars CloudWatch retention.
      cloudWatchLogsRetention:      logs.RetentionDays.FIVE_YEARS,
      managementEvents:             ct.ReadWriteType.ALL,
      insightTypes: [
      ],
    });
    // S3 object-level data events (PCI-DSS / FedRAMP demand these).
    trail.addS3EventSelector([{ bucket: this.centralLogsBucket }], {
      readWriteType:            ct.ReadWriteType.ALL,
      includeManagementEvents:  false,
    });
  }
}