// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — NetworkStack — per-(account,region) VPCs + multi-region TGW
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import { Stack, aws_ec2 as ec2, aws_logs as logs, Fn, RemovalPolicy, Duration } from 'aws-cdk-lib';
// AWS Network Firewall is only used by the centralized-inspection VPC; in a
// distributed-egress LZ the import would be dead code.
import { aws_networkfirewall as networkfirewall } from 'aws-cdk-lib';
// Direct Connect constructs are only used when wizard section 05 enables DX.
import { aws_directconnect as directconnect } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';

// Subnet CIDRs come from generators/aws_vpc_subnet_plan.py so the layout is
// byte-equivalent across LZA / OpenTofu / CDK / tfvars.

export interface NetworkStackProps extends LzStackProps {
  // One stack per (account, region): VPCs (and the TGW) materialize only when
  // both match, so hub lands in Network and spokes in their workload account,
  // each in the correct region.
  readonly accountName: string;
  readonly regionName: string;
  // RAM-shared TGW ids keyed by region. CloudFormation cannot reference a TGW
  // in another account, so a spoke VPC's attachment uses the shared id supplied
  // here (replace the PLACEHOLDER_TGW_ID default with the real shared id, or
  // wire it from an SSM parameter).
  readonly sharedTransitGatewayIds?: Record<string, string>;
  // Cross-account TGW attachment ids keyed by VPC name. The TGW owner (Network)
  // associates/propagates a spoke's attachment to a route domain, but the
  // attachment is created in the spoke's own account, so its id must be passed
  // in (SSM parameter / stack output). Same-account attachments resolve locally.
  readonly sharedTransitGatewayAttachmentIds?: Record<string, string>;
  // Inter-region TGW peering attachment ids keyed by peering name. The peering
  // attachment is created in the requester (primary) region; the accepter
  // (secondary) region cannot reference it across stacks, so its id is passed
  // in here (SSM parameter / stack output) to wire the DR-side route tables.
  readonly sharedTransitGatewayPeeringAttachmentIds?: Record<string, string>;
}

export class NetworkStack extends Stack {
  public readonly vpcs: Record<string, ec2.CfnVPC> = {};

  constructor(scope: Construct, id: string, props: NetworkStackProps) {
    super(scope, id, props);

    // TGWs created in this stack instance, keyed by region (for same-account
    // attachments + the peering requester).
    const tgwByRegion: Record<string, ec2.CfnTransitGateway> = {};
    // Route-domain route tables + attachments created here (centralized egress),
    // declared at constructor scope so the association block after the VPC loop
    // can reference them across the per-(account,region) `if` blocks.
    const routeDomainRt: Record<string, ec2.CfnTransitGatewayRouteTable> = {};
    // Secondary (DR) TGW route tables, keyed by resource id — a DR-region
    // attachment associates here (route domains are primary-only).
    const secondaryTgwRt: Record<string, ec2.CfnTransitGatewayRouteTable> = {};
    const tgwAttachmentByVpc: Record<string, ec2.CfnTransitGatewayVpcAttachment> = {};
    // Inter-region peering attachment, keyed by peering name. Created in the
    // requester (primary) region; the accepter (secondary) region resolves the
    // same id cross-stack via props.
    const peeringAttachmentByName: Record<string, ec2.CfnTransitGatewayPeeringAttachment> = {};
    const tgwIdFor = (region: string): string =>
      tgwByRegion[region]?.ref ?? props.sharedTransitGatewayIds?.[region] ?? 'PLACEHOLDER_TGW_ID';
    const attachmentIdFor = (vpc: string): string =>
      tgwAttachmentByVpc[vpc]?.ref ?? props.sharedTransitGatewayAttachmentIds?.[vpc] ?? 'PLACEHOLDER_TGW_ATTACHMENT_ID';
    const peeringAttachmentIdFor = (name: string): string =>
      peeringAttachmentByName[name]?.ref ?? props.sharedTransitGatewayPeeringAttachmentIds?.[name] ?? 'PLACEHOLDER_TGW_ATTACHMENT_ID';

    // ----- Transit Gateways (Network account, one per region) -----
    if (props.accountName === "Network" && props.regionName === "eu-central-1") {
      const tgwPrimary = new ec2.CfnTransitGateway(this, "PrimaryTgw", {
        amazonSideAsn:                64512,
        autoAcceptSharedAttachments:  'enable',
        defaultRouteTableAssociation: 'disable',
        defaultRouteTablePropagation: 'disable',
        dnsSupport:                   'enable',
        vpnEcmpSupport:               'enable',
        description:                  "main-tgw",
      });
      tgwByRegion["eu-central-1"] = tgwPrimary;
      // Centralized inspection: the primary TGW route tables are route DOMAINS.
      routeDomainRt["main_tgw_inspection"] = new ec2.CfnTransitGatewayRouteTable(this, "RdMainTgwInspection", {
        transitGatewayId: tgwPrimary.ref,
        tags: [{ key: 'Name', value: "main-tgw-inspection" }],
      });
      routeDomainRt["main_tgw_spokes"] = new ec2.CfnTransitGatewayRouteTable(this, "RdMainTgwSpokes", {
        transitGatewayId: tgwPrimary.ref,
        tags: [{ key: 'Name', value: "main-tgw-spokes" }],
      });
      routeDomainRt["main_tgw_cde"] = new ec2.CfnTransitGatewayRouteTable(this, "RdMainTgwCde", {
        transitGatewayId: tgwPrimary.ref,
        tags: [{ key: 'Name', value: "main-tgw-cde" }],
      });
    }
    if (props.accountName === "Network" && props.regionName === "eu-west-1") {
      const tgwSecondary = new ec2.CfnTransitGateway(this, "SecondaryTgw", {
        amazonSideAsn:                64513,
        autoAcceptSharedAttachments:  'enable',
        defaultRouteTableAssociation: 'disable',
        defaultRouteTablePropagation: 'disable',
        dnsSupport:                   'enable',
        vpnEcmpSupport:               'enable',
        description:                  "main-tgw-west",
      });
      tgwByRegion["eu-west-1"] = tgwSecondary;
      // Secondary (DR) TGW: route DOMAINS exist only on the primary TGW, so a
      // DR-region attachment associates to this TGW's OWN tables. DR egress
      // reaches the inspection stack over the inter-region peering.
      secondaryTgwRt["main_tgw_west_associations"] = new ec2.CfnTransitGatewayRouteTable(this, "SecMainTgwWestAssociations", {
        transitGatewayId: tgwSecondary.ref,
        tags: [{ key: 'Name', value: "main-tgw-west-Associations" }],
      });
      secondaryTgwRt["main_tgw_west_propagations"] = new ec2.CfnTransitGatewayRouteTable(this, "SecMainTgwWestPropagations", {
        transitGatewayId: tgwSecondary.ref,
        tags: [{ key: 'Name', value: "main-tgw-west-Propagations" }],
      });
    }

    // ----- VPCs (+ TGW attachment to the regional TGW) -----
    if (props.accountName === "Network" && props.regionName === "eu-central-1") {
      const inspectionVpc = new ec2.CfnVPC(this, "InspectionVpc", {
        cidrBlock:          "10.0.0.0/16",
        enableDnsHostnames: true,
        enableDnsSupport:   true,
      });
      this.vpcs["inspection"] = inspectionVpc;
      const insppublicaSubnet = new ec2.CfnSubnet(this, "InspPublicA", {
        vpcId:               inspectionVpc.ref,
        availabilityZone:    "eu-central-1a",
        cidrBlock:           "10.0.0.0/24",
        mapPublicIpOnLaunch: true,
        tags: [
          { key: 'Name', value: "insp-public-a" },
          { key: 'aws-cdk:subnet-type', value: "Public" },
        ],
      });
      const insppublicbSubnet = new ec2.CfnSubnet(this, "InspPublicB", {
        vpcId:               inspectionVpc.ref,
        availabilityZone:    "eu-central-1b",
        cidrBlock:           "10.0.1.0/24",
        mapPublicIpOnLaunch: true,
        tags: [
          { key: 'Name', value: "insp-public-b" },
          { key: 'aws-cdk:subnet-type', value: "Public" },
        ],
      });
      const inspprivateaSubnet = new ec2.CfnSubnet(this, "InspPrivateA", {
        vpcId:               inspectionVpc.ref,
        availabilityZone:    "eu-central-1a",
        cidrBlock:           "10.0.10.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "insp-private-a" },
          { key: 'aws-cdk:subnet-type', value: "Private" },
        ],
      });
      const inspprivatebSubnet = new ec2.CfnSubnet(this, "InspPrivateB", {
        vpcId:               inspectionVpc.ref,
        availabilityZone:    "eu-central-1b",
        cidrBlock:           "10.0.11.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "insp-private-b" },
          { key: 'aws-cdk:subnet-type', value: "Private" },
        ],
      });
      const inspisolatedaSubnet = new ec2.CfnSubnet(this, "InspIsolatedA", {
        vpcId:               inspectionVpc.ref,
        availabilityZone:    "eu-central-1a",
        cidrBlock:           "10.0.20.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "insp-isolated-a" },
          { key: 'aws-cdk:subnet-type', value: "Isolated" },
        ],
      });
      const inspisolatedbSubnet = new ec2.CfnSubnet(this, "InspIsolatedB", {
        vpcId:               inspectionVpc.ref,
        availabilityZone:    "eu-central-1b",
        cidrBlock:           "10.0.21.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "insp-isolated-b" },
          { key: 'aws-cdk:subnet-type', value: "Isolated" },
        ],
      });
      new ec2.CfnVPCEndpoint(this, "InspectionS3Endpoint", {
        vpcId:           inspectionVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.s3`,
        vpcEndpointType: 'Gateway',
      });
      new ec2.CfnVPCEndpoint(this, "InspectionDynamoDbEndpoint", {
        vpcId:           inspectionVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.dynamodb`,
        vpcEndpointType: 'Gateway',
      });

      // Flow logs (365-day retention; matches the org log floor).
      const inspectionFlowLogGroup = new logs.LogGroup(this, "InspectionFlowLogs", {
        retention:     logs.RetentionDays.ONE_YEAR,
        removalPolicy: RemovalPolicy.RETAIN,
      });
      new ec2.CfnFlowLog(this, "InspectionFlowLog", {
        resourceId:         inspectionVpc.ref,
        resourceType:       'VPC',
        trafficType:        'ALL',
        logDestinationType: 'cloud-watch-logs',
        logGroupName:       inspectionFlowLogGroup.logGroupName,
      });
      // ----- Centralized inspection VPC data plane (IGW + per-AZ NAT + AWS
      // Network Firewall) — mirrors the OpenTofu hand-rolled chain. -----
      const inspectionIgw = new ec2.CfnInternetGateway(this, 'InspectionIgw', {});
      const inspectionIgwAttach = new ec2.CfnVPCGatewayAttachment(this, 'InspectionIgwAttach', {
        vpcId:             inspectionVpc.ref,
        internetGatewayId: inspectionIgw.ref,
      });
      const insppublicaEip = new ec2.CfnEIP(this, "InspPublicAEip", { domain: 'vpc' });
      const insppublicaNatgw = new ec2.CfnNatGateway(this, "InspPublicANatgw", {
        subnetId:     insppublicaSubnet.ref,
        allocationId: insppublicaEip.attrAllocationId,
      });
      const insppublicbEip = new ec2.CfnEIP(this, "InspPublicBEip", { domain: 'vpc' });
      const insppublicbNatgw = new ec2.CfnNatGateway(this, "InspPublicBNatgw", {
        subnetId:     insppublicbSubnet.ref,
        allocationId: insppublicbEip.attrAllocationId,
      });

      // AWS Network Firewall: managed strict-order stateful rule groups.
      const inspectionNfwPolicy = new networkfirewall.CfnFirewallPolicy(this, 'InspectionNfwPolicy', {
        firewallPolicyName: "inspection-nfw-policy",
        firewallPolicy: {
          statelessDefaultActions:         ['aws:forward_to_sfe'],
          statelessFragmentDefaultActions: ['aws:forward_to_sfe'],
          statefulEngineOptions:           { ruleOrder: "STRICT_ORDER" },
          statefulDefaultActions:          ["aws:drop_established", "aws:alert_established"],
          statefulRuleGroupReferences: [
            { resourceArn: `arn:aws:network-firewall:${this.region}:aws-managed:stateful-rulegroup/AWSManagedRulesBotNetCommandAndControlDomainsStrictOrder`, priority: 100 },
            { resourceArn: `arn:aws:network-firewall:${this.region}:aws-managed:stateful-rulegroup/AWSManagedRulesMalwareDomainsStrictOrder`, priority: 200 },
            { resourceArn: `arn:aws:network-firewall:${this.region}:aws-managed:stateful-rulegroup/AWSManagedRulesAbusedLegitMalwareDomainsStrictOrder`, priority: 300 },
          ],
        },
      });
      const inspectionNfw = new networkfirewall.CfnFirewall(this, 'InspectionNfw', {
        firewallName:      "inspection-nfw",
        firewallPolicyArn: inspectionNfwPolicy.attrFirewallPolicyArn,
        vpcId:             inspectionVpc.ref,
        subnetMappings: [
          { subnetId: inspprivateaSubnet.ref },
          { subnetId: inspprivatebSubnet.ref },
        ],
      });
      // Per-AZ endpoint id from the "az:vpce-id" pairs (order matches the
      // subnetMappings order above).
      const inspectionFwEndpoint = (i: number): string =>
        Fn.select(1, Fn.split(':', Fn.select(i, inspectionNfw.attrEndpointIds)));

      const inspectionFlowAlertLg = new logs.LogGroup(this, 'InspectionNfwAlertLogs', {
        retention: logs.RetentionDays.ONE_YEAR, removalPolicy: RemovalPolicy.RETAIN });
      const inspectionFlowFlowLg = new logs.LogGroup(this, 'InspectionNfwFlowLogs', {
        retention: logs.RetentionDays.ONE_YEAR, removalPolicy: RemovalPolicy.RETAIN });
      new networkfirewall.CfnLoggingConfiguration(this, 'InspectionNfwLogging', {
        firewallArn: inspectionNfw.ref,
        loggingConfiguration: {
          logDestinationConfigs: [
            { logType: 'ALERT', logDestinationType: 'CloudWatchLogs', logDestination: { logGroup: inspectionFlowAlertLg.logGroupName } },
            { logType: 'FLOW',  logDestinationType: 'CloudWatchLogs', logDestination: { logGroup: inspectionFlowFlowLg.logGroupName } },
          ],
        },
      });

      // Appliance-mode attachment to the TGW (dedicated per-AZ TGW subnets).
      const inspectionTgwAttachment = new ec2.CfnTransitGatewayVpcAttachment(this, "InspectionTgwAttachment", {
        transitGatewayId: tgwIdFor("eu-central-1"),
        vpcId:            inspectionVpc.ref,
        subnetIds:        [inspisolatedaSubnet.ref, inspisolatedbSubnet.ref],
        options:          { applianceModeSupport: 'enable' },
      });
      tgwAttachmentByVpc["inspection"] = inspectionTgwAttachment;

      // Per-AZ route tables: TGW subnet -> firewall endpoint; firewall subnet ->
      // NAT (+ spoke return -> TGW); NAT subnet -> IGW (+ spoke return -> firewall).
      const inspisolatedaRt = new ec2.CfnRouteTable(this, "InspIsolatedARt", { vpcId: inspectionVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "InspIsolatedARtAssoc", { subnetId: inspisolatedaSubnet.ref, routeTableId: inspisolatedaRt.ref });
      new ec2.CfnRoute(this, "InspIsolatedADefaultRoute", { routeTableId: inspisolatedaRt.ref, destinationCidrBlock: '0.0.0.0/0', vpcEndpointId: inspectionFwEndpoint(0) });

      const inspprivateaRt = new ec2.CfnRouteTable(this, "InspPrivateARt", { vpcId: inspectionVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "InspPrivateARtAssoc", { subnetId: inspprivateaSubnet.ref, routeTableId: inspprivateaRt.ref });
      new ec2.CfnRoute(this, "InspPrivateADefaultRoute", { routeTableId: inspprivateaRt.ref, destinationCidrBlock: '0.0.0.0/0', natGatewayId: insppublicaNatgw.ref });
      (new ec2.CfnRoute(this, "InspPrivateAReturn0", { routeTableId: inspprivateaRt.ref, destinationCidrBlock: "10.1.0.0/16", transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(inspectionTgwAttachment);
      (new ec2.CfnRoute(this, "InspPrivateAReturn1", { routeTableId: inspprivateaRt.ref, destinationCidrBlock: "10.4.0.0/16", transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(inspectionTgwAttachment);
      (new ec2.CfnRoute(this, "InspPrivateAReturn2", { routeTableId: inspprivateaRt.ref, destinationCidrBlock: "10.10.0.0/16", transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(inspectionTgwAttachment);
      (new ec2.CfnRoute(this, "InspPrivateAReturn3", { routeTableId: inspprivateaRt.ref, destinationCidrBlock: "10.11.0.0/16", transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(inspectionTgwAttachment);

      const insppublicaRt = new ec2.CfnRouteTable(this, "InspPublicARt", { vpcId: inspectionVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "InspPublicARtAssoc", { subnetId: insppublicaSubnet.ref, routeTableId: insppublicaRt.ref });
      (new ec2.CfnRoute(this, "InspPublicADefaultRoute", { routeTableId: insppublicaRt.ref, destinationCidrBlock: '0.0.0.0/0', gatewayId: inspectionIgw.ref })).addDependency(inspectionIgwAttach);
      new ec2.CfnRoute(this, "InspPublicAReturn0", { routeTableId: insppublicaRt.ref, destinationCidrBlock: "10.1.0.0/16", vpcEndpointId: inspectionFwEndpoint(0) });
      new ec2.CfnRoute(this, "InspPublicAReturn1", { routeTableId: insppublicaRt.ref, destinationCidrBlock: "10.4.0.0/16", vpcEndpointId: inspectionFwEndpoint(0) });
      new ec2.CfnRoute(this, "InspPublicAReturn2", { routeTableId: insppublicaRt.ref, destinationCidrBlock: "10.10.0.0/16", vpcEndpointId: inspectionFwEndpoint(0) });
      new ec2.CfnRoute(this, "InspPublicAReturn3", { routeTableId: insppublicaRt.ref, destinationCidrBlock: "10.11.0.0/16", vpcEndpointId: inspectionFwEndpoint(0) });
      const inspisolatedbRt = new ec2.CfnRouteTable(this, "InspIsolatedBRt", { vpcId: inspectionVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "InspIsolatedBRtAssoc", { subnetId: inspisolatedbSubnet.ref, routeTableId: inspisolatedbRt.ref });
      new ec2.CfnRoute(this, "InspIsolatedBDefaultRoute", { routeTableId: inspisolatedbRt.ref, destinationCidrBlock: '0.0.0.0/0', vpcEndpointId: inspectionFwEndpoint(1) });

      const inspprivatebRt = new ec2.CfnRouteTable(this, "InspPrivateBRt", { vpcId: inspectionVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "InspPrivateBRtAssoc", { subnetId: inspprivatebSubnet.ref, routeTableId: inspprivatebRt.ref });
      new ec2.CfnRoute(this, "InspPrivateBDefaultRoute", { routeTableId: inspprivatebRt.ref, destinationCidrBlock: '0.0.0.0/0', natGatewayId: insppublicbNatgw.ref });
      (new ec2.CfnRoute(this, "InspPrivateBReturn0", { routeTableId: inspprivatebRt.ref, destinationCidrBlock: "10.1.0.0/16", transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(inspectionTgwAttachment);
      (new ec2.CfnRoute(this, "InspPrivateBReturn1", { routeTableId: inspprivatebRt.ref, destinationCidrBlock: "10.4.0.0/16", transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(inspectionTgwAttachment);
      (new ec2.CfnRoute(this, "InspPrivateBReturn2", { routeTableId: inspprivatebRt.ref, destinationCidrBlock: "10.10.0.0/16", transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(inspectionTgwAttachment);
      (new ec2.CfnRoute(this, "InspPrivateBReturn3", { routeTableId: inspprivatebRt.ref, destinationCidrBlock: "10.11.0.0/16", transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(inspectionTgwAttachment);

      const insppublicbRt = new ec2.CfnRouteTable(this, "InspPublicBRt", { vpcId: inspectionVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "InspPublicBRtAssoc", { subnetId: insppublicbSubnet.ref, routeTableId: insppublicbRt.ref });
      (new ec2.CfnRoute(this, "InspPublicBDefaultRoute", { routeTableId: insppublicbRt.ref, destinationCidrBlock: '0.0.0.0/0', gatewayId: inspectionIgw.ref })).addDependency(inspectionIgwAttach);
      new ec2.CfnRoute(this, "InspPublicBReturn0", { routeTableId: insppublicbRt.ref, destinationCidrBlock: "10.1.0.0/16", vpcEndpointId: inspectionFwEndpoint(1) });
      new ec2.CfnRoute(this, "InspPublicBReturn1", { routeTableId: insppublicbRt.ref, destinationCidrBlock: "10.4.0.0/16", vpcEndpointId: inspectionFwEndpoint(1) });
      new ec2.CfnRoute(this, "InspPublicBReturn2", { routeTableId: insppublicbRt.ref, destinationCidrBlock: "10.10.0.0/16", vpcEndpointId: inspectionFwEndpoint(1) });
      new ec2.CfnRoute(this, "InspPublicBReturn3", { routeTableId: insppublicbRt.ref, destinationCidrBlock: "10.11.0.0/16", vpcEndpointId: inspectionFwEndpoint(1) });
    }
    if (props.accountName === "AppProd" && props.regionName === "eu-central-1") {
      const workloadsVpc = new ec2.CfnVPC(this, "WorkloadsVpc", {
        cidrBlock:          "10.1.0.0/16",
        enableDnsHostnames: true,
        enableDnsSupport:   true,
      });
      this.vpcs["workloads"] = workloadsVpc;
      const wlprivateaSubnet = new ec2.CfnSubnet(this, "WlPrivateA", {
        vpcId:               workloadsVpc.ref,
        availabilityZone:    "eu-central-1a",
        cidrBlock:           "10.1.10.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "wl-private-a" },
          { key: 'aws-cdk:subnet-type', value: "Private" },
        ],
      });
      const wlprivatebSubnet = new ec2.CfnSubnet(this, "WlPrivateB", {
        vpcId:               workloadsVpc.ref,
        availabilityZone:    "eu-central-1b",
        cidrBlock:           "10.1.11.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "wl-private-b" },
          { key: 'aws-cdk:subnet-type', value: "Private" },
        ],
      });
      const wlisolatedaSubnet = new ec2.CfnSubnet(this, "WlIsolatedA", {
        vpcId:               workloadsVpc.ref,
        availabilityZone:    "eu-central-1a",
        cidrBlock:           "10.1.20.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "wl-isolated-a" },
          { key: 'aws-cdk:subnet-type', value: "Isolated" },
        ],
      });
      const wlisolatedbSubnet = new ec2.CfnSubnet(this, "WlIsolatedB", {
        vpcId:               workloadsVpc.ref,
        availabilityZone:    "eu-central-1b",
        cidrBlock:           "10.1.21.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "wl-isolated-b" },
          { key: 'aws-cdk:subnet-type', value: "Isolated" },
        ],
      });
      new ec2.CfnVPCEndpoint(this, "WorkloadsS3Endpoint", {
        vpcId:           workloadsVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.s3`,
        vpcEndpointType: 'Gateway',
      });
      new ec2.CfnVPCEndpoint(this, "WorkloadsDynamoDbEndpoint", {
        vpcId:           workloadsVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.dynamodb`,
        vpcEndpointType: 'Gateway',
      });

      // Flow logs (365-day retention; matches the org log floor).
      const workloadsFlowLogGroup = new logs.LogGroup(this, "WorkloadsFlowLogs", {
        retention:     logs.RetentionDays.ONE_YEAR,
        removalPolicy: RemovalPolicy.RETAIN,
      });
      new ec2.CfnFlowLog(this, "WorkloadsFlowLog", {
        resourceId:         workloadsVpc.ref,
        resourceType:       'VPC',
        trafficType:        'ALL',
        logDestinationType: 'cloud-watch-logs',
        logGroupName:       workloadsFlowLogGroup.logGroupName,
      });
      // Spoke: attach to the TGW and default to it (no local internet egress).
      const workloadsTgwAttachment = new ec2.CfnTransitGatewayVpcAttachment(this, "WorkloadsTgwAttachment", {
        transitGatewayId: tgwIdFor("eu-central-1"),
        vpcId:            workloadsVpc.ref,
        subnetIds:        [wlisolatedaSubnet.ref, wlisolatedbSubnet.ref],
      });
      tgwAttachmentByVpc["workloads"] = workloadsTgwAttachment;
      const wlprivateaRt = new ec2.CfnRouteTable(this, "WlPrivateARt", { vpcId: workloadsVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "WlPrivateARtAssoc", { subnetId: wlprivateaSubnet.ref, routeTableId: wlprivateaRt.ref });
      (new ec2.CfnRoute(this, "WlPrivateADefaultRoute", { routeTableId: wlprivateaRt.ref, destinationCidrBlock: '0.0.0.0/0', transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(workloadsTgwAttachment);
      const wlprivatebRt = new ec2.CfnRouteTable(this, "WlPrivateBRt", { vpcId: workloadsVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "WlPrivateBRtAssoc", { subnetId: wlprivatebSubnet.ref, routeTableId: wlprivatebRt.ref });
      (new ec2.CfnRoute(this, "WlPrivateBDefaultRoute", { routeTableId: wlprivatebRt.ref, destinationCidrBlock: '0.0.0.0/0', transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(workloadsTgwAttachment);
    }
    if (props.accountName === "SharedServices" && props.regionName === "eu-central-1") {
      const sharedservicesVpc = new ec2.CfnVPC(this, "SharedServicesVpc", {
        cidrBlock:          "10.4.0.0/16",
        enableDnsHostnames: true,
        enableDnsSupport:   true,
      });
      this.vpcs["shared-services"] = sharedservicesVpc;
      const sharedprivateaSubnet = new ec2.CfnSubnet(this, "SharedPrivateA", {
        vpcId:               sharedservicesVpc.ref,
        availabilityZone:    "eu-central-1a",
        cidrBlock:           "10.4.10.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "shared-private-a" },
          { key: 'aws-cdk:subnet-type', value: "Private" },
        ],
      });
      const sharedprivatebSubnet = new ec2.CfnSubnet(this, "SharedPrivateB", {
        vpcId:               sharedservicesVpc.ref,
        availabilityZone:    "eu-central-1b",
        cidrBlock:           "10.4.11.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "shared-private-b" },
          { key: 'aws-cdk:subnet-type', value: "Private" },
        ],
      });
      const sharedisolatedaSubnet = new ec2.CfnSubnet(this, "SharedIsolatedA", {
        vpcId:               sharedservicesVpc.ref,
        availabilityZone:    "eu-central-1a",
        cidrBlock:           "10.4.20.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "shared-isolated-a" },
          { key: 'aws-cdk:subnet-type', value: "Isolated" },
        ],
      });
      const sharedisolatedbSubnet = new ec2.CfnSubnet(this, "SharedIsolatedB", {
        vpcId:               sharedservicesVpc.ref,
        availabilityZone:    "eu-central-1b",
        cidrBlock:           "10.4.21.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "shared-isolated-b" },
          { key: 'aws-cdk:subnet-type', value: "Isolated" },
        ],
      });
      new ec2.CfnVPCEndpoint(this, "SharedServicesS3Endpoint", {
        vpcId:           sharedservicesVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.s3`,
        vpcEndpointType: 'Gateway',
      });
      new ec2.CfnVPCEndpoint(this, "SharedServicesDynamoDbEndpoint", {
        vpcId:           sharedservicesVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.dynamodb`,
        vpcEndpointType: 'Gateway',
      });

      // Flow logs (365-day retention; matches the org log floor).
      const sharedservicesFlowLogGroup = new logs.LogGroup(this, "SharedServicesFlowLogs", {
        retention:     logs.RetentionDays.ONE_YEAR,
        removalPolicy: RemovalPolicy.RETAIN,
      });
      new ec2.CfnFlowLog(this, "SharedServicesFlowLog", {
        resourceId:         sharedservicesVpc.ref,
        resourceType:       'VPC',
        trafficType:        'ALL',
        logDestinationType: 'cloud-watch-logs',
        logGroupName:       sharedservicesFlowLogGroup.logGroupName,
      });
      // Spoke: attach to the TGW and default to it (no local internet egress).
      const sharedservicesTgwAttachment = new ec2.CfnTransitGatewayVpcAttachment(this, "SharedServicesTgwAttachment", {
        transitGatewayId: tgwIdFor("eu-central-1"),
        vpcId:            sharedservicesVpc.ref,
        subnetIds:        [sharedisolatedaSubnet.ref, sharedisolatedbSubnet.ref],
      });
      tgwAttachmentByVpc["shared-services"] = sharedservicesTgwAttachment;
      const sharedprivateaRt = new ec2.CfnRouteTable(this, "SharedPrivateARt", { vpcId: sharedservicesVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "SharedPrivateARtAssoc", { subnetId: sharedprivateaSubnet.ref, routeTableId: sharedprivateaRt.ref });
      (new ec2.CfnRoute(this, "SharedPrivateADefaultRoute", { routeTableId: sharedprivateaRt.ref, destinationCidrBlock: '0.0.0.0/0', transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(sharedservicesTgwAttachment);
      const sharedprivatebRt = new ec2.CfnRouteTable(this, "SharedPrivateBRt", { vpcId: sharedservicesVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "SharedPrivateBRtAssoc", { subnetId: sharedprivatebSubnet.ref, routeTableId: sharedprivatebRt.ref });
      (new ec2.CfnRoute(this, "SharedPrivateBDefaultRoute", { routeTableId: sharedprivatebRt.ref, destinationCidrBlock: '0.0.0.0/0', transitGatewayId: tgwIdFor("eu-central-1") })).addDependency(sharedservicesTgwAttachment);
    }
    if (props.accountName === "Network" && props.regionName === "eu-west-1") {
      const hubwestVpc = new ec2.CfnVPC(this, "HubWestVpc", {
        cidrBlock:          "10.10.0.0/16",
        enableDnsHostnames: true,
        enableDnsSupport:   true,
      });
      this.vpcs["hub-west"] = hubwestVpc;
      const hubwesttgwaSubnet = new ec2.CfnSubnet(this, "HubWestTgwA", {
        vpcId:               hubwestVpc.ref,
        availabilityZone:    "eu-west-1a",
        cidrBlock:           "10.10.0.0/28",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "hub-west-tgw-a" },
          { key: 'aws-cdk:subnet-type', value: "Isolated" },
        ],
      });
      const hubwesttgwbSubnet = new ec2.CfnSubnet(this, "HubWestTgwB", {
        vpcId:               hubwestVpc.ref,
        availabilityZone:    "eu-west-1b",
        cidrBlock:           "10.10.0.16/28",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "hub-west-tgw-b" },
          { key: 'aws-cdk:subnet-type', value: "Isolated" },
        ],
      });
      new ec2.CfnVPCEndpoint(this, "HubWestS3Endpoint", {
        vpcId:           hubwestVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.s3`,
        vpcEndpointType: 'Gateway',
      });
      new ec2.CfnVPCEndpoint(this, "HubWestDynamoDbEndpoint", {
        vpcId:           hubwestVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.dynamodb`,
        vpcEndpointType: 'Gateway',
      });

      // Flow logs (365-day retention; matches the org log floor).
      const hubwestFlowLogGroup = new logs.LogGroup(this, "HubWestFlowLogs", {
        retention:     logs.RetentionDays.ONE_YEAR,
        removalPolicy: RemovalPolicy.RETAIN,
      });
      new ec2.CfnFlowLog(this, "HubWestFlowLog", {
        resourceId:         hubwestVpc.ref,
        resourceType:       'VPC',
        trafficType:        'ALL',
        logDestinationType: 'cloud-watch-logs',
        logGroupName:       hubwestFlowLogGroup.logGroupName,
      });
      // Spoke: attach to the TGW and default to it (no local internet egress).
      const hubwestTgwAttachment = new ec2.CfnTransitGatewayVpcAttachment(this, "HubWestTgwAttachment", {
        transitGatewayId: tgwIdFor("eu-west-1"),
        vpcId:            hubwestVpc.ref,
        subnetIds:        [hubwesttgwaSubnet.ref, hubwesttgwbSubnet.ref],
      });
      tgwAttachmentByVpc["hub-west"] = hubwestTgwAttachment;
    }
    if (props.accountName === "AppProd" && props.regionName === "eu-west-1") {
      const workloadswestVpc = new ec2.CfnVPC(this, "WorkloadsWestVpc", {
        cidrBlock:          "10.11.0.0/16",
        enableDnsHostnames: true,
        enableDnsSupport:   true,
      });
      this.vpcs["workloads-west"] = workloadswestVpc;
      const wlwestprivateaSubnet = new ec2.CfnSubnet(this, "WlWestPrivateA", {
        vpcId:               workloadswestVpc.ref,
        availabilityZone:    "eu-west-1a",
        cidrBlock:           "10.11.10.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "wl-west-private-a" },
          { key: 'aws-cdk:subnet-type', value: "Private" },
        ],
      });
      const wlwestprivatebSubnet = new ec2.CfnSubnet(this, "WlWestPrivateB", {
        vpcId:               workloadswestVpc.ref,
        availabilityZone:    "eu-west-1b",
        cidrBlock:           "10.11.11.0/24",
        mapPublicIpOnLaunch: false,
        tags: [
          { key: 'Name', value: "wl-west-private-b" },
          { key: 'aws-cdk:subnet-type', value: "Private" },
        ],
      });
      new ec2.CfnVPCEndpoint(this, "WorkloadsWestS3Endpoint", {
        vpcId:           workloadswestVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.s3`,
        vpcEndpointType: 'Gateway',
      });
      new ec2.CfnVPCEndpoint(this, "WorkloadsWestDynamoDbEndpoint", {
        vpcId:           workloadswestVpc.ref,
        serviceName:     `com.amazonaws.${this.region}.dynamodb`,
        vpcEndpointType: 'Gateway',
      });
      const workloadswestVpceSg = new ec2.CfnSecurityGroup(this, "WorkloadsWestVpceSg", {
        groupDescription: "HTTPS to interface VPC endpoints from within workloads-west",
        vpcId:            workloadswestVpc.ref,
        securityGroupIngress: [{ ipProtocol: 'tcp', fromPort: 443, toPort: 443, cidrIp: "10.11.0.0/16", description: 'HTTPS from the VPC CIDR' }],
      });
      new ec2.CfnVPCEndpoint(this, "WorkloadsWestEc2Endpoint", {
        vpcId:             workloadswestVpc.ref,
        serviceName:       `com.amazonaws.${this.region}.ec2`,
        vpcEndpointType:   'Interface',
        privateDnsEnabled: true,
        subnetIds:         [wlwestprivateaSubnet.ref, wlwestprivatebSubnet.ref],
        securityGroupIds:  [workloadswestVpceSg.attrGroupId],
      });
      new ec2.CfnVPCEndpoint(this, "WorkloadsWestSsmEndpoint", {
        vpcId:             workloadswestVpc.ref,
        serviceName:       `com.amazonaws.${this.region}.ssm`,
        vpcEndpointType:   'Interface',
        privateDnsEnabled: true,
        subnetIds:         [wlwestprivateaSubnet.ref, wlwestprivatebSubnet.ref],
        securityGroupIds:  [workloadswestVpceSg.attrGroupId],
      });
      new ec2.CfnVPCEndpoint(this, "WorkloadsWestSecretsmanagerEndpoint", {
        vpcId:             workloadswestVpc.ref,
        serviceName:       `com.amazonaws.${this.region}.secretsmanager`,
        vpcEndpointType:   'Interface',
        privateDnsEnabled: true,
        subnetIds:         [wlwestprivateaSubnet.ref, wlwestprivatebSubnet.ref],
        securityGroupIds:  [workloadswestVpceSg.attrGroupId],
      });
      new ec2.CfnVPCEndpoint(this, "WorkloadsWestLogsEndpoint", {
        vpcId:             workloadswestVpc.ref,
        serviceName:       `com.amazonaws.${this.region}.logs`,
        vpcEndpointType:   'Interface',
        privateDnsEnabled: true,
        subnetIds:         [wlwestprivateaSubnet.ref, wlwestprivatebSubnet.ref],
        securityGroupIds:  [workloadswestVpceSg.attrGroupId],
      });

      // Flow logs (365-day retention; matches the org log floor).
      const workloadswestFlowLogGroup = new logs.LogGroup(this, "WorkloadsWestFlowLogs", {
        retention:     logs.RetentionDays.ONE_YEAR,
        removalPolicy: RemovalPolicy.RETAIN,
      });
      new ec2.CfnFlowLog(this, "WorkloadsWestFlowLog", {
        resourceId:         workloadswestVpc.ref,
        resourceType:       'VPC',
        trafficType:        'ALL',
        logDestinationType: 'cloud-watch-logs',
        logGroupName:       workloadswestFlowLogGroup.logGroupName,
      });
      // Spoke: attach to the TGW and default to it (no local internet egress).
      const workloadswestTgwAttachment = new ec2.CfnTransitGatewayVpcAttachment(this, "WorkloadsWestTgwAttachment", {
        transitGatewayId: tgwIdFor("eu-west-1"),
        vpcId:            workloadswestVpc.ref,
        subnetIds:        [wlwestprivateaSubnet.ref, wlwestprivatebSubnet.ref],
      });
      tgwAttachmentByVpc["workloads-west"] = workloadswestTgwAttachment;
      const wlwestprivateaRt = new ec2.CfnRouteTable(this, "WlWestPrivateARt", { vpcId: workloadswestVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "WlWestPrivateARtAssoc", { subnetId: wlwestprivateaSubnet.ref, routeTableId: wlwestprivateaRt.ref });
      (new ec2.CfnRoute(this, "WlWestPrivateADefaultRoute", { routeTableId: wlwestprivateaRt.ref, destinationCidrBlock: '0.0.0.0/0', transitGatewayId: tgwIdFor("eu-west-1") })).addDependency(workloadswestTgwAttachment);
      const wlwestprivatebRt = new ec2.CfnRouteTable(this, "WlWestPrivateBRt", { vpcId: workloadswestVpc.ref });
      new ec2.CfnSubnetRouteTableAssociation(this, "WlWestPrivateBRtAssoc", { subnetId: wlwestprivatebSubnet.ref, routeTableId: wlwestprivatebRt.ref });
      (new ec2.CfnRoute(this, "WlWestPrivateBDefaultRoute", { routeTableId: wlwestprivatebRt.ref, destinationCidrBlock: '0.0.0.0/0', transitGatewayId: tgwIdFor("eu-west-1") })).addDependency(workloadswestTgwAttachment);
    }
    // ----- Inter-region peering (warm-standby DR path) -----
    // Created before the route-table wiring below so the primary-region routing
    // block can reference the peering attachment it just made.
    if (props.accountName === "Network" && props.regionName === "eu-central-1") {
      peeringAttachmentByName["primary-to-secondary"] = new ec2.CfnTransitGatewayPeeringAttachment(this, "PrimaryToSecondaryPeering", {
        transitGatewayId:     tgwIdFor("eu-central-1"),
        peerTransitGatewayId: tgwIdFor("eu-west-1"),
        peerAccountId:        this.account,
        peerRegion:           "eu-west-1",
      });
    }

    // ----- Centralized routing (primary TGW): associate each primary-region
    // attachment to its route domain, propagate spoke CIDRs into the inspection
    // domain, and static-route each spoke domain's default at the inspection
    // attachment (TGW owner = Network). Spoke attachment ids are cross-account,
    // supplied via props.
    if (props.accountName === "Network" && props.regionName === "eu-central-1") {
      new ec2.CfnTransitGatewayRouteTableAssociation(this, "InspectionAssoc", {
        transitGatewayAttachmentId:    attachmentIdFor("inspection"),
        transitGatewayRouteTableId:    routeDomainRt["main_tgw_inspection"].ref,
      });
      new ec2.CfnTransitGatewayRouteTableAssociation(this, "WorkloadsAssoc", {
        transitGatewayAttachmentId:    attachmentIdFor("workloads"),
        transitGatewayRouteTableId:    routeDomainRt["main_tgw_spokes"].ref,
      });
      new ec2.CfnTransitGatewayRouteTablePropagation(this, "WorkloadsPropMainTgwInspection", {
        transitGatewayAttachmentId:    attachmentIdFor("workloads"),
        transitGatewayRouteTableId:    routeDomainRt["main_tgw_inspection"].ref,
      });
      new ec2.CfnTransitGatewayRouteTableAssociation(this, "SharedServicesAssoc", {
        transitGatewayAttachmentId:    attachmentIdFor("shared-services"),
        transitGatewayRouteTableId:    routeDomainRt["main_tgw_spokes"].ref,
      });
      new ec2.CfnTransitGatewayRouteTablePropagation(this, "SharedServicesPropMainTgwInspection", {
        transitGatewayAttachmentId:    attachmentIdFor("shared-services"),
        transitGatewayRouteTableId:    routeDomainRt["main_tgw_inspection"].ref,
      });
      new ec2.CfnTransitGatewayRoute(this, "EgressMainTgwSpokes", {
        destinationCidrBlock:          "0.0.0.0/0",
        transitGatewayRouteTableId:    routeDomainRt["main_tgw_spokes"].ref,
        transitGatewayAttachmentId:    attachmentIdFor("inspection"),
      });
      // Associate the inter-region peering to the spokes domain so DR traffic
      // arriving over the peering takes the same 0.0.0.0/0 -> inspection route.
      new ec2.CfnTransitGatewayRouteTableAssociation(this, "PrimaryToSecondaryPriAssoc", {
        transitGatewayAttachmentId:    peeringAttachmentIdFor("primary-to-secondary"),
        transitGatewayRouteTableId:    routeDomainRt["main_tgw_spokes"].ref,
      });
      // Post-firewall return path: route the DR CIDR back over the peering.
      new ec2.CfnTransitGatewayRoute(this, "PeerBackPrimaryToSecondary1", {
        destinationCidrBlock:          "10.10.0.0/16",
        transitGatewayRouteTableId:    routeDomainRt["main_tgw_inspection"].ref,
        transitGatewayAttachmentId:    peeringAttachmentIdFor("primary-to-secondary"),
      });
      // Post-firewall return path: route the DR CIDR back over the peering.
      new ec2.CfnTransitGatewayRoute(this, "PeerBackPrimaryToSecondary2", {
        destinationCidrBlock:          "10.11.0.0/16",
        transitGatewayRouteTableId:    routeDomainRt["main_tgw_inspection"].ref,
        transitGatewayAttachmentId:    peeringAttachmentIdFor("primary-to-secondary"),
      });
    }
    // ----- Centralized routing (secondary/DR TGW): DR-region attachments
    // associate to this TGW's own tables; the association table default-routes
    // 0.0.0.0/0 over the peering so DR egress is inspected in the primary region.
    if (props.accountName === "Network" && props.regionName === "eu-west-1") {
      new ec2.CfnTransitGatewayRouteTableAssociation(this, "HubWestAssoc", {
        transitGatewayAttachmentId:    attachmentIdFor("hub-west"),
        transitGatewayRouteTableId:    secondaryTgwRt["main_tgw_west_associations"].ref,
      });
      new ec2.CfnTransitGatewayRouteTablePropagation(this, "HubWestPropMainTgwWestAssociations", {
        transitGatewayAttachmentId:    attachmentIdFor("hub-west"),
        transitGatewayRouteTableId:    secondaryTgwRt["main_tgw_west_associations"].ref,
      });
      new ec2.CfnTransitGatewayRouteTablePropagation(this, "HubWestPropMainTgwWestPropagations", {
        transitGatewayAttachmentId:    attachmentIdFor("hub-west"),
        transitGatewayRouteTableId:    secondaryTgwRt["main_tgw_west_propagations"].ref,
      });
      new ec2.CfnTransitGatewayRouteTableAssociation(this, "WorkloadsWestAssoc", {
        transitGatewayAttachmentId:    attachmentIdFor("workloads-west"),
        transitGatewayRouteTableId:    secondaryTgwRt["main_tgw_west_associations"].ref,
      });
      new ec2.CfnTransitGatewayRouteTablePropagation(this, "WorkloadsWestPropMainTgwWestAssociations", {
        transitGatewayAttachmentId:    attachmentIdFor("workloads-west"),
        transitGatewayRouteTableId:    secondaryTgwRt["main_tgw_west_associations"].ref,
      });
      new ec2.CfnTransitGatewayRouteTablePropagation(this, "WorkloadsWestPropMainTgwWestPropagations", {
        transitGatewayAttachmentId:    attachmentIdFor("workloads-west"),
        transitGatewayRouteTableId:    secondaryTgwRt["main_tgw_west_propagations"].ref,
      });
      new ec2.CfnTransitGatewayRouteTableAssociation(this, "PrimaryToSecondarySecAssoc", {
        transitGatewayAttachmentId:    peeringAttachmentIdFor("primary-to-secondary"),
        transitGatewayRouteTableId:    secondaryTgwRt["main_tgw_west_associations"].ref,
      });
      new ec2.CfnTransitGatewayRoute(this, "PeerEgressPrimaryToSecondary1", {
        destinationCidrBlock:          "0.0.0.0/0",
        transitGatewayRouteTableId:    secondaryTgwRt["main_tgw_west_associations"].ref,
        transitGatewayAttachmentId:    peeringAttachmentIdFor("primary-to-secondary"),
      });
    }

    // Hybrid connectivity lives in the Network account / home region. External
    // dependencies the wizard cannot create (DX circuit, on-prem IPs, ACM/SAML
    // material) are PLACEHOLDER_ tokens — see PLACEHOLDERS.md.
    if (props.accountName === "Network" && props.regionName === "eu-central-1") {
      // ⚠️ Direct Connect VIF type is 'private', but this landing zone routes through a Transit Gateway and has no virtual private gateway for a private VIF to bind to. Use a 'transit' VIF (it associates the Direct Connect Gateway to the Transit Gateway for multi-VPC reach), or attach a VGW to the target VPC before deploying.
      // DXGW Amazon-side ASN 64514 is distinct from the customer ASN 64512 (eBGP).
      const onprem_dxgwDxgw = new directconnect.CfnDirectConnectGateway(this, "OnpremDxgwDxgw", {
        name:          "onprem-dxgw",
        amazonSideAsn: 64514,
      });
      new directconnect.CfnPrivateVirtualInterface(this, "PrimaryVifVif", {
        connectionId: "PLACEHOLDER_DX_CONNECTION_ID",
        privateVirtualInterface: {
          virtualInterfaceName: "primary-vif",
          vlan:                 100,
          asn:                  64512,
          directConnectGatewayId: onprem_dxgwDxgw.ref,
          addressFamily:        'ipv4',
        },
      });
    }
  }
}