// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — OrganizationsStack — OU tree + service-access principals
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import { Stack, StackProps, aws_organizations as orgs } from 'aws-cdk-lib';
import { Construct } from 'constructs';

export interface LzStackProps extends StackProps {
  readonly orgName: string;
  readonly profile: string;
  readonly tags: Record<string, string>;
}

export class OrganizationsStack extends Stack {
  // OU path ('Workloads/Prod/PHI') -> created OU id. Exposed so the
  // AccountsStack parents each account to the real OU instead of a placeholder.
  public readonly ouIds: Record<string, string> = {};

  constructor(scope: Construct, id: string, props: LzStackProps) {
    super(scope, id, props);

    // Root ID has to be supplied externally; CDK cannot create roots.
    const rootId = this.node.tryGetContext('organizationRootId') as string
      ?? 'PLACEHOLDER_ROOT_ID';
    this.ouIds['Root'] = rootId;

    // OU tree — single source of truth: generators/aws_ou_tree.py. The same
    // tree drives OpenTofu / LZA / tfvars, so every format creates an identical
    // OU hierarchy (profile baseline + custom OUs + every OU path an account is
    // assigned to, e.g. Workloads/Prod/PHI). Nodes arrive parent-before-child,
    // so each parentId lookup below is already populated.
    const ouSecurity = new orgs.CfnOrganizationalUnit(this, "SecurityOU", {
      name:     "Security",
      parentId: this.ouIds['Root'],
    });
    this.ouIds["Security"] = ouSecurity.attrId;
    const ouWorkloads = new orgs.CfnOrganizationalUnit(this, "WorkloadsOU", {
      name:     "Workloads",
      parentId: this.ouIds['Root'],
    });
    this.ouIds["Workloads"] = ouWorkloads.attrId;
    const ouSuspended = new orgs.CfnOrganizationalUnit(this, "SuspendedOU", {
      name:     "Suspended",
      parentId: this.ouIds['Root'],
    });
    this.ouIds["Suspended"] = ouSuspended.attrId;
    const ouInfrastructure = new orgs.CfnOrganizationalUnit(this, "InfrastructureOU", {
      name:     "Infrastructure",
      parentId: this.ouIds['Root'],
    });
    this.ouIds["Infrastructure"] = ouInfrastructure.attrId;
    const ouPolicystaging = new orgs.CfnOrganizationalUnit(this, "PolicystagingOU", {
      name:     "PolicyStaging",
      parentId: this.ouIds['Root'],
    });
    this.ouIds["PolicyStaging"] = ouPolicystaging.attrId;
    const ouWorkloadsSandbox = new orgs.CfnOrganizationalUnit(this, "WorkloadsSandboxOU", {
      name:     "Sandbox",
      parentId: this.ouIds["Workloads"],
    });
    this.ouIds["Workloads/Sandbox"] = ouWorkloadsSandbox.attrId;
    const ouWorkloadsDev = new orgs.CfnOrganizationalUnit(this, "WorkloadsDevOU", {
      name:     "Dev",
      parentId: this.ouIds["Workloads"],
    });
    this.ouIds["Workloads/Dev"] = ouWorkloadsDev.attrId;
    const ouWorkloadsStaging = new orgs.CfnOrganizationalUnit(this, "WorkloadsStagingOU", {
      name:     "Staging",
      parentId: this.ouIds["Workloads"],
    });
    this.ouIds["Workloads/Staging"] = ouWorkloadsStaging.attrId;
    const ouWorkloadsProd = new orgs.CfnOrganizationalUnit(this, "WorkloadsProdOU", {
      name:     "Prod",
      parentId: this.ouIds["Workloads"],
    });
    this.ouIds["Workloads/Prod"] = ouWorkloadsProd.attrId;

    const ouIds = this.ouIds;

    // Service Control Policies — set sourced from generators/aws_scp_policies.py
    // so every format enforces the same guardrails (Quarantine, deny disabling
    // CloudTrail/Config/GuardDuty/Security Hub, sandbox cost guardrails, region
    // restrictions).
    new orgs.CfnPolicy(this, "QuarantinePolicy", {
      name:        "Quarantine-Policy",
      description: "Deny all actions for newly created accounts until reviewed.",
      type:        'SERVICE_CONTROL_POLICY',
      content:     {"Statement": [{"Action": "*", "Condition": {"ArnNotLikeIfExists": {"aws:PrincipalArn": ["arn:aws:iam::*:role/OrganizationAccountAccessRole", "arn:aws:iam::*:role/AWSControlTowerExecution"]}}, "Effect": "Deny", "Resource": "*", "Sid": "DenyAllNewAccounts"}], "Version": "2012-10-17"},
      targetIds:   [ouIds["Suspended"]],
    });
    new orgs.CfnPolicy(this, "GuardrailsSecurityPolicy", {
      name:        "Guardrails-Security",
      description: "Deny disabling CloudTrail/Config/GuardDuty/Security Hub. Attached to Workloads + Infrastructure — every member account that must never turn off a security service. The Security OU is intentionally excluded: it holds the delegated administrator (Audit), which legitimately calls GuardDuty/Security Hub member-management APIs this policy denies. (Targeting only Security — or Root — would either leave workloads unprotected or break the delegated admin.)",
      type:        'SERVICE_CONTROL_POLICY',
      content:     {"Statement": [{"Action": ["cloudtrail:StopLogging", "cloudtrail:DeleteTrail", "cloudtrail:PutEventSelectors", "cloudtrail:UpdateTrail"], "Effect": "Deny", "Resource": "*", "Sid": "DenyDisableCloudTrail"}, {"Action": ["config:DeleteConfigurationRecorder", "config:StopConfigurationRecorder", "config:DeleteDeliveryChannel", "config:DeleteConfigRule", "config:DeleteOrganizationConfigRule"], "Effect": "Deny", "Resource": "*", "Sid": "DenyDisableConfig"}, {"Action": ["guardduty:DeleteDetector", "guardduty:UpdateDetector", "guardduty:DisassociateFromMasterAccount", "guardduty:DisassociateMembers", "guardduty:DeleteMembers", "guardduty:StopMonitoringMembers"], "Effect": "Deny", "Resource": "*", "Sid": "DenyDisableGuardDuty"}, {"Action": ["securityhub:DisableSecurityHub", "securityhub:DisassociateFromAdministratorAccount", "securityhub:DeleteMembers", "securityhub:DisassociateMembers"], "Effect": "Deny", "Resource": "*", "Sid": "DenyDisableSecurityHub"}], "Version": "2012-10-17"},
      targetIds:   [ouIds["Workloads"], ouIds["Infrastructure"]],
    });
    new orgs.CfnPolicy(this, "GuardrailsSandboxPolicy", {
      name:        "Guardrails-Sandbox",
      description: "Cost guardrails for sandbox accounts (deny large/accelerated instance types + long-term capacity purchases). Scoped to the Sandbox OU only so it never restricts production workloads.",
      type:        'SERVICE_CONTROL_POLICY',
      content:     {"Statement": [{"Action": "ec2:RunInstances", "Condition": {"ForAnyValue:StringLike": {"ec2:InstanceType": ["*.4xlarge", "*.8xlarge", "*.12xlarge", "*.16xlarge", "*.24xlarge", "*.32xlarge", "*.48xlarge", "*.metal", "p3.*", "p4.*", "p5.*", "g4.*", "g5.*", "g6.*", "x1.*", "x2.*", "z1d.*", "u-*"]}}, "Effect": "Deny", "Resource": "arn:aws:ec2:*:*:instance/*", "Sid": "DenyLargeAndAcceleratedInstanceTypes"}, {"Action": ["ec2:PurchaseReservedInstancesOffering", "ec2:PurchaseHostReservation", "ec2:PurchaseCapacityBlock", "savingsplans:CreateSavingsPlan", "rds:PurchaseReservedDBInstancesOffering", "elasticache:PurchaseReservedCacheNodesOffering", "redshift:PurchaseReservedNodeOffering", "opensearch:PurchaseReservedInstanceOffering", "es:PurchaseReservedElasticsearchInstanceOffering"], "Effect": "Deny", "Resource": "*", "Sid": "DenyLongTermCapacityPurchases"}], "Version": "2012-10-17"},
      targetIds:   [ouIds["Workloads/Sandbox"]],
    });
    new orgs.CfnPolicy(this, "RegionRestrictionEuPolicy", {
      name:        "Region-Restriction-EUOnly",
      description: "Restrict all account actions to EU regions for data sovereignty.",
      type:        'SERVICE_CONTROL_POLICY',
      content:     {"Statement": [{"Condition": {"StringNotEquals": {"aws:RequestedRegion": ["eu-west-1", "eu-west-2", "eu-west-3", "eu-central-1", "eu-central-2", "eu-north-1", "eu-south-1", "eu-south-2"]}}, "Effect": "Deny", "NotAction": ["a4b:*", "account:*", "aws-marketplace:*", "aws-portal:*", "budgets:*", "ce:*", "cloudfront:*", "cur:*", "globalaccelerator:*", "health:*", "iam:*", "organizations:*", "route53:*", "route53domains:*", "shield:*", "sts:*", "support:*", "trustedadvisor:*", "waf:*", "wafv2:*", "waf-regional:*"], "Resource": "*", "Sid": "DenyNonEURegions"}], "Version": "2012-10-17"},
      targetIds:   [ouIds["Root"]],
    });
    new orgs.CfnPolicy(this, "ProtectSecurityServicesPolicy", {
      name:        "Protect-Security-Services",
      description: "Deny disabling CloudTrail / Config / GuardDuty / Security Hub at any account in the org. NIS2 Art 21 risk-management; FedRAMP/NIST SI-4 + CA-7 monitoring integrity; HIPAA admin safeguards; PCI-DSS Req 10 audit-log protection.",
      type:        'SERVICE_CONTROL_POLICY',
      content:     {"Statement": [{"Action": ["cloudtrail:StopLogging", "cloudtrail:DeleteTrail", "cloudtrail:PutEventSelectors", "cloudtrail:UpdateTrail"], "Effect": "Deny", "Resource": "*", "Sid": "DenyDisableCloudTrail"}, {"Action": ["config:DeleteConfigurationRecorder", "config:StopConfigurationRecorder", "config:DeleteDeliveryChannel", "config:DeleteConfigRule", "config:DeleteOrganizationConfigRule"], "Effect": "Deny", "Resource": "*", "Sid": "DenyDisableConfig"}, {"Action": ["guardduty:DeleteDetector", "guardduty:UpdateDetector", "guardduty:DisassociateFromMasterAccount", "guardduty:DisassociateMembers", "guardduty:DeleteMembers", "guardduty:StopMonitoringMembers"], "Effect": "Deny", "Resource": "*", "Sid": "DenyDisableGuardDuty"}, {"Action": ["securityhub:DisableSecurityHub", "securityhub:DisassociateFromAdministratorAccount", "securityhub:DeleteMembers", "securityhub:DisassociateMembers"], "Effect": "Deny", "Resource": "*", "Sid": "DenyDisableSecurityHub"}], "Version": "2012-10-17"},
      targetIds:   [ouIds["Root"]],
    });
    new orgs.CfnPolicy(this, "RequireImdsv2Policy", {
      name:        "Require-IMDSv2",
      description: "Deny launching EC2 instances without IMDSv2 (http_tokens=required) and deny weakening the metadata options afterwards. Prevention paired with the ec2-imdsv2-check Config rule's detection. CIS 5.4/5.6; NIST/FedRAMP AC-3 + SC-23; PCI-DSS Req 2; HIPAA technical safeguards.",
      type:        'SERVICE_CONTROL_POLICY',
      content:     {"Statement": [{"Action": "ec2:RunInstances", "Condition": {"StringNotEquals": {"ec2:MetadataHttpTokens": "required"}}, "Effect": "Deny", "Resource": "arn:aws:ec2:*:*:instance/*", "Sid": "DenyRunInstancesWithoutImdsv2"}, {"Action": "ec2:ModifyInstanceMetadataOptions", "Condition": {"StringNotEquals": {"ec2:MetadataHttpTokens": "required"}}, "Effect": "Deny", "Resource": "*", "Sid": "DenyDowngradingMetadataOptions"}], "Version": "2012-10-17"},
      targetIds:   [ouIds["Root"]],
    });
    new orgs.CfnPolicy(this, "DenyRootAccessPolicy", {
      name:        "Deny-Root-Access",
      description: "Deny all actions by the account root user (CIS 1.7 / Control Tower 'disallow root' guardrail). Break-glass is preserved: the condition only matches the root principal, so IAM roles/users are unaffected (use a break-glass admin role), and SCPs never apply to the organization management account's root.",
      type:        'SERVICE_CONTROL_POLICY',
      content:     {"Statement": [{"Action": "*", "Condition": {"StringLike": {"aws:PrincipalArn": "arn:aws:iam::*:root"}}, "Effect": "Deny", "Resource": "*", "Sid": "DenyRootUserActions"}], "Version": "2012-10-17"},
      targetIds:   [ouIds["Root"]],
    });
  }
}