// Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

// ---------------------------------------------------------------------------
// Generated by Merlin Studio v2 (architex-v2) — SecurityStack — GuardDuty, Security Hub, Access Analyzer, IAM baseline
// Organization: AcmeCorp
// Profile:      ADVANCED
// Generated:    2026-06-30T07:20:42.670905Z
// Wizard:       v1.0.0
// ---------------------------------------------------------------------------
// Scaffolding — not a finished artifact. Merlin renders this from your
// declared intent (profile, frameworks, accounts, topology). Adapt it to
// your environment: tighten CIDRs, refine policy bodies, add team tags,
// pin construct versions, layer account-specific overrides. Re-run the
// wizard when *intent* shifts; keep day-to-day customisation in your IaC
// fork (regen overwrites this directory).
// Replace PLACEHOLDER_ tokens with real values from your AWS Organization
// before `cdk deploy` — see PLACEHOLDERS.md.

import {
  Stack,
  aws_guardduty as gd,
  aws_securityhub as sh,
  aws_accessanalyzer as aa,
  aws_iam as iam,
  aws_ec2 as ec2,
  custom_resources as cr,
} from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LzStackProps } from './organizations-stack';

export class SecurityStack extends Stack {
  constructor(scope: Construct, id: string, props: LzStackProps) {
    super(scope, id, props);

    // GuardDuty detector + delegated admin (Audit account).
    const detector = new gd.CfnDetector(this, 'GuardDutyDetector', {
      enable:                       true,
      findingPublishingFrequency:   'FIFTEEN_MINUTES',
      dataSources: {
        s3Logs: { enable: true },
        kubernetes: { auditLogs: { enable: true } },
        malwareProtection: { scanEc2InstanceWithFindings: { ebsVolumes: true } },
      },
      // RDS Protection (RDS_LOGIN_EVENTS): on for regulated frameworks or when
      // RDS/Aurora is in use — bank transactional data concentrates there.
      features: [
        { name: 'RDS_LOGIN_EVENTS', status: 'ENABLED' },
      ],
    });
    // Delegate GuardDuty administration to the audit account. There is no
    // CloudFormation resource for org delegated-admin, so call the API directly.
    new cr.AwsCustomResource(this, 'GuardDutyDelegatedAdmin', {
      onCreate: {
        service: 'GuardDuty',
        action:  'enableOrganizationAdminAccount',
        parameters: {
          AdminAccountId: "PLACEHOLDER_ACCOUNT_ID_Audit",
        },
        physicalResourceId: cr.PhysicalResourceId.of('GuardDutyDelegatedAdmin'),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE }),
    });

    // Macie — sensitive-data discovery. Delegate org admin to the audit account,
    // then enable. No CloudFormation resource for org admin, so call the API.
    new cr.AwsCustomResource(this, 'MacieDelegatedAdmin', {
      onCreate: {
        service: 'Macie2',
        action:  'enableOrganizationAdminAccount',
        parameters: { adminAccountId: "PLACEHOLDER_ACCOUNT_ID_Audit" },
        physicalResourceId: cr.PhysicalResourceId.of('MacieDelegatedAdmin'),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE }),
    });
    new cr.AwsCustomResource(this, 'MacieEnable', {
      onCreate: {
        service: 'Macie2',
        action:  'enableMacie',
        parameters: { status: 'ENABLED', findingPublishingFrequency: 'FIFTEEN_MINUTES' },
        physicalResourceId: cr.PhysicalResourceId.of('MacieEnable'),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE }),
    });
    // Amazon Inspector — continuous vulnerability scanning (ECR/EC2/Lambda).
    // Delegate org admin to the audit account, then enable for the resource types.
    new cr.AwsCustomResource(this, 'InspectorDelegatedAdmin', {
      onCreate: {
        service: 'Inspector2',
        action:  'enableDelegatedAdminAccount',
        parameters: { delegatedAdminAccountId: "PLACEHOLDER_ACCOUNT_ID_Audit" },
        physicalResourceId: cr.PhysicalResourceId.of('InspectorDelegatedAdmin'),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE }),
    });
    new cr.AwsCustomResource(this, 'InspectorEnable', {
      onCreate: {
        service: 'Inspector2',
        action:  'enable',
        parameters: { resourceTypes: ['ECR', 'EC2', 'LAMBDA'] },
        physicalResourceId: cr.PhysicalResourceId.of('InspectorEnable'),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE }),
    });

    // Security Hub + finding aggregator
    const shHub = new sh.CfnHub(this, 'SecurityHub', {
      enableDefaultStandards: false,
      tags:                   props.tags,
    });
    new sh.CfnFindingAggregator(this, 'SecurityHubAggregator', {
      regionLinkingMode: 'ALL_REGIONS',
    });

    new sh.CfnStandard(this, "AwsFoundationalSecurityBestPracticesV100", {
      standardsArn: "arn:aws:securityhub:::ruleset/aws-foundational-security-best-practices/v/1.0.0",
    }).addDependency(shHub);
    new sh.CfnStandard(this, "CisAwsFoundationsBenchmarkV140", {
      standardsArn: "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.4.0",
    }).addDependency(shHub);
    new sh.CfnStandard(this, "Nist80053V500", {
      standardsArn: "arn:aws:securityhub:::ruleset/nist-800-53/v/5.0.0",
    }).addDependency(shHub);

    // IAM Access Analyzer (organization scope)
    new aa.CfnAnalyzer(this, 'OrgAccessAnalyzer', {
      analyzerName: 'org-analyzer',
      type:         'ORGANIZATION',
    });

    // Org-wide IAM password policy (CIS 1.5–1.11).
    new cr.AwsCustomResource(this, 'IamPasswordPolicy', {
      onCreate: {
        service: 'IAM',
        action:  'updateAccountPasswordPolicy',
        parameters: {
          MinimumPasswordLength:        14,
          RequireSymbols:               true,
          RequireNumbers:               true,
          RequireUppercaseCharacters:   true,
          RequireLowercaseCharacters:   true,
          AllowUsersToChangePassword:   true,
          MaxPasswordAge:               60,
          PasswordReusePrevention:      24,
          HardExpiry:                   false,
        },
        physicalResourceId: cr.PhysicalResourceId.of('IamPasswordPolicy'),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE }),
    });

    // Org-wide S3 public-access block (defends against accidental
    // public buckets even when bucket-level settings are wrong).
    // Account-level S3 public-access block has no CloudFormation resource;
    // set it via the S3 Control API.
    new cr.AwsCustomResource(this, 'AccountPublicAccessBlock', {
      onCreate: {
        service: 'S3Control',
        action:  'putPublicAccessBlock',
        parameters: {
          AccountId: this.account,
          PublicAccessBlockConfiguration: {
            BlockPublicAcls:       true,
            BlockPublicPolicy:     true,
            IgnorePublicAcls:      true,
            RestrictPublicBuckets: true,
          },
        },
        physicalResourceId: cr.PhysicalResourceId.of('AccountPublicAccessBlock'),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE }),
    });

    // Org-wide EBS default volume encryption (CIS 2.2.1).
    const ebsEnc = new cr.AwsCustomResource(this, 'EbsDefaultEncryption', {
      onCreate: {
        service: 'EC2',
        action:  'enableEbsEncryptionByDefault',
        parameters: {},
        physicalResourceId: cr.PhysicalResourceId.of('EbsDefaultEncryption'),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE }),
    });
    // encryption_requirements=cmk -> point the regional default EBS key at the
    // workload CMK (alias/accelerator/kms/key), not the AWS-managed key.
    const ebsCmk = new cr.AwsCustomResource(this, 'EbsDefaultKmsKey', {
      onCreate: {
        service: 'EC2',
        action:  'modifyEbsDefaultKmsKeyId',
        parameters: { KmsKeyId: "alias/accelerator/kms/key" },
        physicalResourceId: cr.PhysicalResourceId.of('EbsDefaultKmsKey'),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE }),
    });
    ebsCmk.node.addDependency(ebsEnc);
  }
}